# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W8U4ehCFdKD31YwS4N5cH0315bckn6YD
"""

print("---CALCULADORA---")
num1 = int(input("Ingrese un numero: "))
num2 = int(input("ingrese otro numero: "))
while True:
  print("Menu de opciones")
  print("1- Sumar")
  print("2- Restar")
  print("3- Dividir")
  print("4- Multiplicar")
  opc = int(input("Ingrese una opcion: "))
  if opc == 1:
    print("La sumas es: ", num1 + num2)
    break
  elif opc ==2:
    print("La resta es: ", num1 - num2)
    break
  elif opc ==3:
    print("La divicion es: ", num1 / num2)
    break
  elif opc == 4:
    print("la multiplicacion es: ", num1 * num2)
    break